name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]       # main에 push 시 자동 배포
  workflow_dispatch:           # 수동 실행 허용

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: dist
      REMOTE_DIR: /var/www/youthjob
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT || 22 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (Vite → dist/)
        run: npm run build

      # 임시 릴리스 디렉토리 이름 생성 (SHA 기반)
      - name: Prepare release name
        id: prep
        run: echo "REL=release_${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # 서버에 임시 폴더 생성
      - name: Create temp dir on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            mkdir -p /tmp/${{ steps.prep.outputs.REL }}

      # dist 업로드 → /tmp/REL 로
      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          source: "${{ env.BUILD_DIR }}/*"
          target: "/tmp/${{ steps.prep.outputs.REL }}/"

      # 원자적 교체(다운타임 최소화) + 권한 정리 + Nginx 리로드
      - name: Activate release
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            set -e
            # 보조: 대상 디렉터리 존재/소유권 보장
            sudo mkdir -p /var/www/youthjob
            sudo chown -R $USER:$USER /var/www/youthjob

            # 업로드한 빌드(/tmp/release_xxx) → /var/www/youthjob 로 동기화 (원자적, 권장)
            rsync -a --delete "/tmp/${{ steps.prep.outputs.REL }}/" "/var/www/youthjob/"

            # 권한 정리(정적 서빙용)
            find /var/www/youthjob -type d -exec chmod 755 {} \;
            find /var/www/youthjob -type f -exec chmod 644 {} \;

            # Nginx 재적용
            sudo nginx -t && sudo systemctl reload nginx